{"name": "test_get_saved_tracks_limit", "status": "failed", "statusDetails": {"message": "AssertionError: Wrong status code, expected 429\nassert 403 == 429", "trace": "self = <test_tracks.TestTracks object at 0x0000022039A8C050>, log_test_name = None\n\n    @pytest.mark.functional\n    def test_get_saved_tracks_limit(self, log_test_name):\n        \"\"\"\n        Test get saved tracks\n        Get a list of the songs saved in the current Spotify user's 'Your Music' library.\n        \"\"\"\n        url_saved_tracks = f\"{self.url_tracks_me}?limit={LIMIT_TRACKS}\"\n        LOGGER.info(\"The URL of saved tracks over limit allowed: %s\", url_saved_tracks)\n    \n        response = self.rest_client.request(\"get\", url=url_saved_tracks)\n        LOGGER.info(\"The saved tracks: %s\", response)\n    \n>       assert response[\"status_code\"] == 429, \"Wrong status code, expected 429\"\nE       AssertionError: Wrong status code, expected 429\nE       assert 403 == 429\n\nspotify_api\\tracks\\test_tracks.py:48: AssertionError"}, "description": "\n        Test get saved tracks\n        Get a list of the songs saved in the current Spotify user's 'Your Music' library.\n        ", "start": 1712025079586, "stop": 1712025079924, "uuid": "a6f165ae-ed56-43c9-85b6-39c00240d7d1", "historyId": "7913f251210b11477a8f03c59343f884", "testCaseId": "7913f251210b11477a8f03c59343f884", "fullName": "spotify_api.tracks.test_tracks.TestTracks#test_get_saved_tracks_limit", "labels": [{"name": "tag", "value": "functional"}, {"name": "parentSuite", "value": "spotify_api.tracks"}, {"name": "suite", "value": "test_tracks"}, {"name": "subSuite", "value": "TestTracks"}, {"name": "host", "value": "LBUITRONP-DH02"}, {"name": "thread", "value": "14272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "spotify_api.tracks.test_tracks"}]}